# Automatically approves pull requests if:
#   1. The PR was opened by Dependabot
#   2. The dependency's semantic versioning change is either minor or patch (not major)
name: Dependabot auto-approve
on:
  pull_request_target: {}
  pull_request: {}


permissions:
  pull-requests: write
  contents: write

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
      - name: Approve a PR if dependency semver changes are minor or patch
        if: ${{contains(fromJson('["version-update:semver-patch", "version-update:semver-minor"]'), steps.dependabot-metadata.outputs.update-type)}}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge if dependency semver changes are minor or patch
        if: ${{contains(fromJson('["version-update:semver-patch", "version-update:semver-minor"]'), steps.dependabot-metadata.outputs.update-type)}}
        run: |
          echo "Enabling auto-merge for Dependabot $UPDATE_TYPE"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          UPDATE_TYPE: ${{steps.dependabot-metadata.outputs.update-type}}
